name: KIP
description: $description
version: '${version}'

main: org.Textureless.kip.KIP
api-version: '1.21'
load: STARTUP

authors: [ NoBodyIDK, JustEvil ]

permissions:
  KIP.group.default:
    description: "Default group permission for default users."
    default: true